### ISSUE TITLE
Create a bash script for executing the cpp code and diff the outputs

### ISSUE THREAD

**Issue by kaushik-rishi** [kaushik-rishi/rocketcp#1]
- Create a bash script that creates the executable 
- Which when run from the problem folder validates the inputs with the outputs

**Comment by Sukriti-sood** [comment]
@kaushik-rishi  I would like to work  on this issue .

**Comment by Ruchip16** [comment]
@kaushik-rishi  I am interested to work on this issue, may I?

**Comment by knavdeep152002** [comment]
@kaushik-rishi I am interested to create a bash script, Can you assign me this issue?

**Comment by kaushik-rishi** [comment]
Yeah sure. I'll assign this issue to 3 of you. Create a directory in the `src` folder called `execution_scripts` and add the bash script.
If you have any doubts ask it in the comments section. Ready to help.

**Comment by Ruchip16** [comment]
@kaushik-rishi How to get started with the issue any guidelines for contributing are given by you previously coz I am unable to find them
