### ISSUE TITLE
Static Root Directory

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [kaushik-rishi/rocketcp#15]
New Feature :

> Presently the root directory is static and fixed as the home directory of the user.
> But generally we don't do competitive programming in our home directory.
> Thus the user should be provided with a option to change the root. 

We can achieve this using any option below : 

> .env files 
> user input on server start.

**Comment by kaushik-rishi** [comment]
Would'nt it be better if we had a dot file in the home directory storing all the configuration settings of the user.
Including the directory location ?
I was planning to add this feature.
We can work together

**Comment by Shubham-Kumar-2000** [comment]
Yes we can make .rocketcp.json file.

**Comment by Shubham-Kumar-2000** [comment]
Or we can even go for a .rocketcp.env and dotenv module will take care of the rest.

**Comment by kaushik-rishi** [comment]
The super set issue should solve this issue as well.
Please look at Issue #29
