### ISSUE TITLE
Enhancement of the previous Issue Mentioned

### ISSUE THREAD

**Issue by Yash1256** [kaushik-rishi/rocketcp#16]
@kaushik-rishi as in Issue #1 you have mentioned to make a bash script which when run from the problem(s) folder and will validates the Input and Output. As for an Idea It would be simple to follow the above but it wouldn't be better.

 My Idea is - If we make our own command and it automatically compiles and check for the Input and Output, through this the bash script will not be there in each and every folder and It would be easier for the person to just type a command and check his code.
 `
 A Sample Command as : cp check
`

What do you say about this? If you like I would love to work on this Issue.

**Comment by kaushik-rishi** [comment]
@srisatya1197 Did you understand the issue. Describe the work plan you are thinking of implement to solve this issue.

**Comment by kaushik-rishi** [comment]
@Yash1256 This issue will come to focus once the makefile layer below this will be resolved.

**Comment by kaushik-rishi** [comment]
@Yash1256 Make a branch and start working on it.
If you think that it would be better to work on this issue in the later stages of the project, This issue will be closed and will be reopened again.
