### ISSUE TITLE
Youtube link on GSSSOC'21 website for Rocket Competitive Programming is incorrect

### ISSUE THREAD

**Issue by Siddharth1006** [kaushik-rishi/rocketcp#19]
https://www.youtube.com/watch?v=3hCQKaUxKRQ
// correct link

This should be the link. But on the GSSOC'21 website the link given is this : https://www.youtube.com/watch?v=2TUyVUQhMb8
The above link redirects to RocketMeet. 

@kaushik-rishi please resolve this.

**Comment by kaushik-rishi** [comment]
Oh no! A bad mistake on their side. Will contact them asap and get it resolved.

**Comment by Siddharth1006** [comment]
Ok.

**Comment by kaushik-rishi** [comment]
Thanks for pointing out

**Comment by kaushik-rishi** [comment]
@Siddharth1006 Fixed
