### ISSUE TITLE
Embed a Makefile into each problem folder 

### ISSUE THREAD

**Issue by kaushik-rishi** [kaushik-rishi/rocketcp#2]
- While creating the problem folder and the problem files 
      - Create a Makefile in the directory 
      - Which generates the executable
      - Which tests the input and output of code

**Comment by Shubham-Kumar-2000** [comment]
Can I work on this under GSSOC 21 ?

**Comment by kaushik-rishi** [comment]
Sure. I've assigned the task. Do look at the work done by the other people on the bash script branch so that you can pull up some ideas from there.

- create a make file and ensure it is working
- then make a PR adding the makefile to the `src/assets` folder
- then move to editing the server.js to embed a makefile into each of these problem folders.

Don't hesitate to ask for help.

**Comment by Shubham-Kumar-2000** [comment]
I cannot find any bash script branch

**Comment by kaushik-rishi** [comment]
@Shubham-Kumar-2000 I mean't people are working on an issue. But never mind proceed with your work.

**Comment by Shubham-Kumar-2000** [comment]
PR adding the makefile to the src/assets folder. Done.

**Comment by kaushik-rishi** [comment]
@Shubham-Kumar-2000 I meant to edit the title, Not create a new PR. Because as you're commits are in this PR.
