### ISSUE TITLE
Gif link broken

### ISSUE THREAD

**Issue by satcasm** [kaushik-rishi/rocketcp#20]
The ``demo.gif`` link seems to be broken.

Reference screenshot:
![image](https://user-images.githubusercontent.com/56315878/110521535-dca54300-8135-11eb-9962-d5203c5457b8.png)

Would like to fix it as a part of GSSOC' 21.

**Comment by sagar-barapatre** [comment]
Yeah ! you can start working on it...

**Comment by satcasm** [comment]
Closing as the issue is resolved.
