### ISSUE TITLE
Create & Improve Tool Documentation

### ISSUE THREAD

**Issue by learneradarsh** [kaushik-rishi/rocketcp#25]
Create documentation having the following points:
1. How this tool can help the user?
2. Who can use this tool?
3. How to do the setup of this tool?
4. How to raise issues if found any?

Here is a small kind of documentation. Please take the idea from this for main documentation creation.
https://github.com/kaushik-rishi/rocketcp/blob/master/HOWTOUSE.md

Please feel free to add your own ideas and suggestions during working.

**Comment by GuptaTanisha** [comment]
@learneradarsh Please assign this to me.

**Comment by learneradarsh** [comment]
> @learneradarsh Please assign this to me.

Assigned to you @GuptaTanisha

**Comment by rk05-lenavo** [comment]
I'm a GSSOC'21 participant kindly assign me this issue under GSSOC'21. I would love to work in this.

**Comment by learneradarsh** [comment]
hi, @rk05-lenavo  could you please pair with @GuptaTanisha because I think she has started working on it else you can pick it up accordingly I will assign you.

**Comment by rk05-lenavo** [comment]
@learneradarsh  could you please assign me I want to `work on it by my own.

**Comment by GuptaTanisha** [comment]
@learneradarsh Sure sir.
