### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [kaushik-rishi/rocketcp#26]
Hi! @kaushik-rishi I would like to update contributing.md by putting steps on how to clone a repo and install on local system ,how to make a branch and use git commands to push it to origin ,How to make a PR , how to update your forkedrepo as well as local repo as the changes are made to the upstream

I would like to work on this as a part  of GSSOC'21

**Comment by learneradarsh** [comment]
Sure @khareyash05 I have assigned you this issue. Please start working on it.

**Comment by learneradarsh** [comment]
@kaushik-rishi Please share if you have inputs for the same.

**Comment by learneradarsh** [comment]
@khareyash05 Do you also want to work on how to use the documentation for a tool?
https://github.com/kaushik-rishi/rocketcp/issues/25

**Comment by kaushik-rishi** [comment]
> @kaushik-rishi Please share if you have inputs for the same.

Yeah.
Please look at the video in the Readme for more details on working of the project also join the server and add the server link at top in the Readme so others can also contribute 

https://discord.gg/axfEwf6K

**Comment by kaushik-rishi** [comment]
> Thanx @learneradarsh I will submit  a PR  by tomorrow morning for sure

@khareyash05 You can talk to me if you have doubts about the working. No need to rush do the job perfectly thats it.

**Comment by khareyash05** [comment]
> > @kaushik-rishi Please share if you have inputs for the same.
> 
> Yeah.
> Please look at the video in the Readme for more details on working of the project also join the server and add the server link at top in the Readme so others can also contribute
> 
> https://discord.gg/axfEwf6K

Hello Sir! @kaushik-rishi I am working on contributing.md ...... 
1. Do I have to add the link in Contributing.md file?
2. Shall I create an issue on adding link to Readme file?

**Comment by khareyash05** [comment]
I am on it @learneradarsh @kaushik-rishi

**Comment by learneradarsh** [comment]
Done

**Comment by khareyash05** [comment]
@learneradarsh could you pls add level label to the same
