### ISSUE TITLE
Convert the bash script into a Makefile

### ISSUE THREAD

**Issue by kaushik-rishi** [kaushik-rishi/rocketcp#3]

**Comment by micksharma** [comment]
I want to work on this issue. Can you please explain it.

**Comment by subhangi2731** [comment]
I want to work on this please assign me

**Comment by kaushik-rishi** [comment]
There is a make file in the `src/assets` folder so you could go and look into it and try to improve it. The bash scripts issue is not resolved yet. Once it its resolved I'll tag you @subhangi2731. It should be done by today.

**Comment by kaushik-rishi** [comment]
> I want to work on this issue. Can you please explain it.

You need to design a bash script that when run in the `problem directory` takes all the test cases and and checks the output and input files and validates the outputs.
After that we basically need to convert it into a `Makefile`. People are working on bash script and there is also a sample makefile in `src/assets` so please look into it.
Also see the sample video and run the project locally to grab a better understanding of it.

**Comment by kaushik-rishi** [comment]
Issue was automatically solved by PR #13
