### ISSUE TITLE
[Issue#34] [Feature Update : Backend] Handle the route creating the configuration file

### ISSUE THREAD

**Issue by kaushik-rishi** [kaushik-rishi/rocketcp#34]
Because:

- We hard coded the values of programming language and template path till commit #57
- Develop a backend and a single frontend ejs file / handlebars anything of that case to handle the user configuration
- This should launch a server and create a configuration file based on it
- The frontend is just a minimal HTML Form with a bunch of attributes that will be added incrementally

This issue is for the developing the **backend** of the application
Issue #33 has close connection with it.

Anyone having doubts can hop into the discord server and discuss with the mentors and fellow contributors

**Comment by subhangi2731** [comment]
can you please assign this issue to me?

**Comment by kaushik-rishi** [comment]
Did you understand the issue ? @subhangi2731 
If yes could you just clarify it so that there would be no feature clashes.
If no then you can join the discord server of the project, I and mentors will guide you for working on this issue

**Comment by kaushik-rishi** [comment]
@subhangi2731 Would you still like to work on this issue ?

**Comment by Kriti-bit** [comment]
I am a participant in GSSOC'21. I would like to work on this, please share some more details regarding this issue.

**Comment by Shubham-Kumar-2000** [comment]
@kaushik-rishi  can you assign me this under gssoc 21?

**Comment by kaushik-rishi** [comment]
@Shubham-Kumar-2000 Go ahead.
