### ISSUE TITLE
Tech Stack Update ( LOGO add ) 

### ISSUE THREAD

**Issue by rohank2502** [kaushik-rishi/rocketcp#37]
I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

**Comment by kaushik-rishi** [comment]
@rohank2502 Start working !
Join the discord server for working on more harder issues and seeking help

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 Start working !
> Join the discord server for working on more harder issues and seeking help

Ok Thank you !!

**Comment by rohank2502** [comment]
Thanks !!

**Comment by rohank2502** [comment]
Which tech stack will you like to be added ?

**Comment by kaushik-rishi** [comment]
Our tech stack is
- Vanilla node js [No frameworks like express js]

That's it.
