### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohank2502** [kaushik-rishi/rocketcp#38]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by kaushik-rishi** [comment]
@rohank2502 This is assigned to you. Go ahead.

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 This is assigned to you. Go ahead.

Thanks !!
