### ISSUE TITLE
[Issue #45] Implement the configuration controllers

### ISSUE THREAD

**Issue by kaushik-rishi** [kaushik-rishi/rocketcp#45]
Because:
- we need stable controllers either for working with the global configuration file or to create a back end going in future.

**Comment by kaushik-rishi** [comment]
I'll be working on this issue. I have given myself a deadline of **today** to complete this issue.
If this is not implemented by today. **Contributors are welcome.**

**Comment by kaushik-rishi** [comment]
I'll be working on this issue. I have given myself a deadline of **today** to complete this issue.
If this is not implemented by today. **Contributors are welcome.**

**Comment by kaushik-rishi** [comment]
TODO : Write tests by tomorrow.
Please mentor me on this issue. @learneradarsh

**Comment by learneradarsh** [comment]
> TODO : Write tests by tomorrow.
> Please mentor me on this issue. @learneradarsh

Use Jest, it will be good.

**Comment by Shubham-Kumar-2000** [comment]
@kaushik-rishi can you assign me this?

**Comment by kaushik-rishi** [comment]
Sure @Shubham-Kumar-2000

**Comment by subhangi2731** [comment]
can you assign me this?
