### ISSUE TITLE
Add language support for Python

### ISSUE THREAD

**Issue by kaushik-rishi** [kaushik-rishi/rocketcp#5]

**Comment by micksharma** [comment]
Hi, I want to work on this issue. Can you please explain it.

**Comment by Shubham-Kumar-2000** [comment]
Hi can I work on this?

**Comment by kaushik-rishi** [comment]
@Shubham-Kumar-2000 @micksharma Any doubt's regarding the work you need to do ?

**Comment by micksharma** [comment]
@kaushik-rishi yeah Can you elaborate little bit

**Comment by Shubham-Kumar-2000** [comment]
No I don't have any doubt on this.

As far as I understood we nee to make a Python template and embed them in each of the problem folder and accordingly update make file to support both cpp and python under different rules.

Can you assign this to me?

**Comment by subhangi2731** [comment]
I really want to work on this please assign me

**Comment by Siddharth1006** [comment]
I am GSSOC'21 participant. I am interested and want to work on this issue.

**Comment by kaushik-rishi** [comment]
> No I don't have any doubt on this.
> 
> As far as I understood we nee to make a Python template and embed them in each of the problem folder and accordingly update make file to support both cpp and python under different rules.
> 
> Can you assign this to me?
> @kaushik-rishi

@Shubham-Kumar-2000 One issue at a time

**Comment by kaushik-rishi** [comment]
> I am GSSOC'21 participant. I am interested and want to work on this issue.

Sorry but it's a first come first server basis. I'll assign if no other contrib. is interested

**Comment by kaushik-rishi** [comment]
@micksharma If you understood the issue. You can work on it else I'll assign it to @subhangi2731 .
You can ask any doubts you have on the discord server.
Or I'll open a gitter channel for this repo

**Comment by Shubham-Kumar-2000** [comment]
@kaushik-rishi 

I have already submitted PRs for previous issues

**Comment by kaushik-rishi** [comment]
@Shubham-Kumar-2000 Assigned the issue.

**Comment by kaushik-rishi** [comment]
@Shubham-Kumar-2000 Completed. PR #Merged python support added
