### ISSUE TITLE
Compute the difference using a better difference algorithm 

### ISSUE THREAD

**Issue by aravindchalla** [kaushik-rishi/rocketcp#54]
I would like you to work on this issue @kaushik-rishi

**Comment by kaushik-rishi** [comment]
Yeah ! Sure will be up with it in an hour.

**Comment by kaushik-rishi** [comment]
I'm working on this on the `refactor-major` branch.
Working update:
- Figured out an npm package to calculate better diff.
- Will embed it into the project

**Comment by aravindchalla** [comment]
Thanks for the update Rishi. I would love to help you with anything if needed.

**Comment by techpkd123** [comment]
Can i also work upon this issue?

**Comment by kaushik-rishi** [comment]
Contact me on the discord server.
Link in the readme. @techpkd123
