### ISSUE TITLE
[Need] Issue and PR template

### ISSUE THREAD

**Issue by Aryamanz29** [kaushik-rishi/rocketcp#56]
Currently, there is no issue and  PR template in this repo

**Comment by Aryamanz29** [comment]
I would like to work on this issue, Please add labels and Kindly assign it to me

**Comment by kaushik-rishi** [comment]
@Aryamanz29 I guess there is a template but make it such that it shows on the issues page.

**Comment by Aryamanz29** [comment]
Kindly review my PR @kaushik-rishi
