### ISSUE TITLE
[Basic Styling] Add a command line spinner to the log message listening to the server

### ISSUE THREAD

**Issue by kaushik-rishi** [kaushik-rishi/rocketcp#59]
### **Feature request**:
In the server.js we are just printing `Listening to post requests ..` on starting the server. We expect it to print a command line spinner and the the text `Server listening ...`

### **Describe the solution you'd like**:
[npm ora](https://www.npmjs.com/package/ora)
- you could use this package to create the spinner

### **Describe alternatives you've considered**:
[another spinner module](https://www.npmjs.com/package/cli-spinners)
- you could also use this if the above package seems bloated

### **Describe how this feature will be useful to our readers**:
It'll make the cli tool more interesting

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Shubham-Kumar-2000** [comment]
Would you like to assign me this??

**Comment by kaushik-rishi** [comment]
Sure @Shubham-Kumar-2000
