### ISSUE TITLE
Execute the bash script / make file using child processes 

### ISSUE THREAD

**Issue by kaushik-rishi** [kaushik-rishi/rocketcp#6]
- Use child processes 
- Basically figure out a way to execute the shell commands without using `make`

**Comment by micksharma** [comment]
Can I work on this issue ?

**Comment by subhangi2731** [comment]
I want to work on this please assign me

**Comment by kaushik-rishi** [comment]
This issue requires resolution of previous issues. Will be reopened once  previous issues are resolved.

**Comment by kaushik-rishi** [comment]
This issue requires resolution of previous issues. Will be reopened once  previous issues are resolved.

**Comment by Shubham-Kumar-2000** [comment]
@kaushik-rishi  can you assign me this.

**Comment by kaushik-rishi** [comment]
@Shubham-Kumar-2000 Go ahead.

**Comment by kaushik-rishi** [comment]
Done ! PR #40 @Shubham-Kumar-2000 Best work
