### ISSUE TITLE
Multiple Ports for Server

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [kaushik-rishi/rocketcp#61]
### **Feature request**:
Give option to user to choose some different port if the pre defined port is busy.

### **Is your feature request related to a problem? Please describe. (optional)**:
If I have another application running on port 10045 then our server fails.

### **Describe the solution you'd like**:
If the default port is busy we will give him option to change the port.
And ask if he wants to change the default port to that.
If yes we can update this in defaults file.

### **Describe alternatives you've considered**:
NA

### **Describe how this feature will be useful to our readers**:
It will provide more flexibility for the users.

### **Additional context:**
NA

<hr/>

@kaushik-rishi  can you assign me this under GsSOC'21

**Comment by kaushik-rishi** [comment]
- Assigned this issue to you @Shubham-Kumar-2000 
[Use this as a reference](https://github.com/jmerle/competitive-companion/blob/master/src/hosts/hosts.ts)
