### ISSUE TITLE
ESlint

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [kaushik-rishi/rocketcp#62]
### **Describe the bug:**
While working on the code I saw some unused functions , useless shebang on each file, etc.
Thus added eslint to avoid these silly mistakes
### **To Reproduce:**
1. Go to any file and you will know

### **Expected behavior:**
NA

### **Screenshots:**
NA

### **Additional context:**
Advantages of Using ESLint

- Toggle Any Rule. ESLint does not enforce strict standards on you. 
- Configuration Levels. ESLint has a configuration hierarchy.
- Community Created Plugins.
- Add Custom Rules, Parsers, and Reporters.
- Easy Migration.
- Great Documentation.

<hr/>

**Note:**
@kaushik-rishi  I have already added a PR regarding this plz look into it.

**Comment by kaushik-rishi** [comment]
- Advantage over prettier as a pre-commit hook:
        - Getting the code suggestions while coding live
        - More flexibility while formatting
