### ISSUE TITLE
Routes Arrangements

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [kaushik-rishi/rocketcp#84]
### **Describe the bug:**

Routes should be in a different file.

### **To Reproduce:**

1. All Routes are written in file src/configuration/server.js 

### **Expected behavior:**

Routes Should be in a different file.

@kaushik-rishi  Can you assign me this under gssoc 21

**Comment by kaushik-rishi** [comment]
@Shubham-Kumar-2000 Assigned. !
