### ISSUE TITLE
Body parser

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [kaushik-rishi/rocketcp#86]
### **Describe the bug:**

Body parser absent in express configuration server 

### **To Reproduce:**

1. Go to src/configuration/server.js

### **Expected behavior:**

Body parser should be there to parse the incoming body.

@kaushik-rishi  Please assign me this

**Comment by kaushik-rishi** [comment]
@Shubham-Kumar-2000 Assigned. !
