### ISSUE TITLE
Load Config

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [kaushik-rishi/rocketcp#89]
### **Feature request**:

To load the config and store it in memory

### **Describe the solution you'd like**:

In app.js require a file to load a config related data.

### **Describe how this feature will be useful to our readers**:

This will help them to use their boiler plate.

@kaushik-rishi  please assign me this.

**Comment by kaushik-rishi** [comment]
Assigned.

**Comment by kaushik-rishi** [comment]
@Shubham-Kumar-2000 Assigned. !
