### ISSUE TITLE
Default Config

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [kaushik-rishi/rocketcp#91]
### **Feature request**:

Setup a default config if the config file is absent or corrupt.

### **Is your feature request related to a problem? Please describe. (optional)**:

When the new user install it the config file is absent thus may crash other functionality.

### **Describe the solution you'd like**:

In loadconfig file if the global.config is null then load the default config.

### **Describe how this feature will be useful to our readers**:

They will get a seamless experience

@kaushik-rishi  please assign me this.

**Comment by kaushik-rishi** [comment]
@Shubham-Kumar-2000 Assigned
